language: java
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - ./gradlew javadoc
after_success:
  - bash <(curl -s https://codecov.io/bash)