#!/usr/bin/env sh

set -e

# Directory containing this file
DIR=$(cd "$(dirname "$0")" && pwd -P)

PROJECT=compiler

(cd "$DIR" && ./gradlew :$PROJECT:installDist > /dev/null) && "$DIR/$PROJECT/build/install/$PROJECT/bin/$PROJECT" "$@" <&0
