/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cornell.cs.apl.viaduct.libsnarkwrapper;

public class LinComb {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LinComb(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LinComb obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsnarkwrapperJNI.delete_LinComb(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setConstTerm(int value) {
    libsnarkwrapperJNI.LinComb_constTerm_set(swigCPtr, this, value);
  }

  public int getConstTerm() {
    return libsnarkwrapperJNI.LinComb_constTerm_get(swigCPtr, this);
  }

  public void setLinTerms(TermVector value) {
    libsnarkwrapperJNI.LinComb_linTerms_set(swigCPtr, this, TermVector.getCPtr(value), value);
  }

  public TermVector getLinTerms() {
    long cPtr = libsnarkwrapperJNI.LinComb_linTerms_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TermVector(cPtr, false);
  }

  public SWIGTYPE_p_libsnark__linear_combinationT_field128_t to_lincomb() {
    return new SWIGTYPE_p_libsnark__linear_combinationT_field128_t(
        libsnarkwrapperJNI.LinComb_to_lincomb(swigCPtr, this), true);
  }

  public LinComb() {
    this(libsnarkwrapperJNI.new_LinComb(), true);
  }
}
