/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cornell.cs.apl.viaduct.libsnarkwrapper;

public class ShaResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ShaResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ShaResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsnarkwrapperJNI.delete_ShaResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVal_var(SWIGTYPE_p_libsnark__pb_variableT_field128_t value) {
    libsnarkwrapperJNI.ShaResult_val_var_set(
        swigCPtr, this, SWIGTYPE_p_libsnark__pb_variableT_field128_t.getCPtr(value));
  }

  public SWIGTYPE_p_libsnark__pb_variableT_field128_t getVal_var() {
    return new SWIGTYPE_p_libsnark__pb_variableT_field128_t(
        libsnarkwrapperJNI.ShaResult_val_var_get(swigCPtr, this), true);
  }

  public void setData(SWIGTYPE_p_libsnark__pb_variable_arrayT_field128_t value) {
    libsnarkwrapperJNI.ShaResult_data_set(
        swigCPtr, this, SWIGTYPE_p_libsnark__pb_variable_arrayT_field128_t.getCPtr(value));
  }

  public SWIGTYPE_p_libsnark__pb_variable_arrayT_field128_t getData() {
    return new SWIGTYPE_p_libsnark__pb_variable_arrayT_field128_t(
        libsnarkwrapperJNI.ShaResult_data_get(swigCPtr, this), true);
  }

  public void setNonce(SWIGTYPE_p_libsnark__pb_variable_arrayT_field128_t value) {
    libsnarkwrapperJNI.ShaResult_nonce_set(
        swigCPtr, this, SWIGTYPE_p_libsnark__pb_variable_arrayT_field128_t.getCPtr(value));
  }

  public SWIGTYPE_p_libsnark__pb_variable_arrayT_field128_t getNonce() {
    return new SWIGTYPE_p_libsnark__pb_variable_arrayT_field128_t(
        libsnarkwrapperJNI.ShaResult_nonce_get(swigCPtr, this), true);
  }

  public void setOutput(SWIGTYPE_p_libsnark__pb_variable_arrayT_field128_t value) {
    libsnarkwrapperJNI.ShaResult_output_set(
        swigCPtr, this, SWIGTYPE_p_libsnark__pb_variable_arrayT_field128_t.getCPtr(value));
  }

  public SWIGTYPE_p_libsnark__pb_variable_arrayT_field128_t getOutput() {
    return new SWIGTYPE_p_libsnark__pb_variable_arrayT_field128_t(
        libsnarkwrapperJNI.ShaResult_output_get(swigCPtr, this), true);
  }

  public ShaResult() {
    this(libsnarkwrapperJNI.new_ShaResult(), true);
  }
}
