/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cornell.cs.apl.viaduct.libsnarkwrapper;

public class WireInfoVector extends java.util.AbstractList<WireInfo>
    implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WireInfoVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WireInfoVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsnarkwrapperJNI.delete_WireInfoVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public WireInfoVector(WireInfo[] initialElements) {
    this();
    reserve(initialElements.length);

    for (WireInfo element : initialElements) {
      add(element);
    }
  }

  public WireInfoVector(Iterable<WireInfo> initialElements) {
    this();
    for (WireInfo element : initialElements) {
      add(element);
    }
  }

  public WireInfo get(int index) {
    return doGet(index);
  }

  public WireInfo set(int index, WireInfo e) {
    return doSet(index, e);
  }

  public boolean add(WireInfo e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, WireInfo e) {
    modCount++;
    doAdd(index, e);
  }

  public WireInfo remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public WireInfoVector() {
    this(libsnarkwrapperJNI.new_WireInfoVector__SWIG_0(), true);
  }

  public WireInfoVector(WireInfoVector other) {
    this(libsnarkwrapperJNI.new_WireInfoVector__SWIG_1(WireInfoVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return libsnarkwrapperJNI.WireInfoVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    libsnarkwrapperJNI.WireInfoVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return libsnarkwrapperJNI.WireInfoVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    libsnarkwrapperJNI.WireInfoVector_clear(swigCPtr, this);
  }

  public WireInfoVector(int count, WireInfo value) {
    this(
        libsnarkwrapperJNI.new_WireInfoVector__SWIG_2(count, WireInfo.getCPtr(value), value), true);
  }

  private int doSize() {
    return libsnarkwrapperJNI.WireInfoVector_doSize(swigCPtr, this);
  }

  private void doAdd(WireInfo x) {
    libsnarkwrapperJNI.WireInfoVector_doAdd__SWIG_0(swigCPtr, this, WireInfo.getCPtr(x), x);
  }

  private void doAdd(int index, WireInfo x) {
    libsnarkwrapperJNI.WireInfoVector_doAdd__SWIG_1(swigCPtr, this, index, WireInfo.getCPtr(x), x);
  }

  private WireInfo doRemove(int index) {
    return new WireInfo(libsnarkwrapperJNI.WireInfoVector_doRemove(swigCPtr, this, index), true);
  }

  private WireInfo doGet(int index) {
    return new WireInfo(libsnarkwrapperJNI.WireInfoVector_doGet(swigCPtr, this, index), false);
  }

  private WireInfo doSet(int index, WireInfo val) {
    return new WireInfo(
        libsnarkwrapperJNI.WireInfoVector_doSet(swigCPtr, this, index, WireInfo.getCPtr(val), val),
        true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    libsnarkwrapperJNI.WireInfoVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }
}
