/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cornell.cs.apl.viaduct.libsnarkwrapper;

public class WireInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WireInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WireInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsnarkwrapperJNI.delete_WireInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(WireType value) {
    libsnarkwrapperJNI.WireInfo_type_set(swigCPtr, this, value.swigValue());
  }

  public WireType getType() {
    return WireType.swigToEnum(libsnarkwrapperJNI.WireInfo_type_get(swigCPtr, this));
  }

  public void setInput_val(int value) {
    libsnarkwrapperJNI.WireInfo_input_val_set(swigCPtr, this, value);
  }

  public int getInput_val() {
    return libsnarkwrapperJNI.WireInfo_input_val_get(swigCPtr, this);
  }

  public WireInfo() {
    this(libsnarkwrapperJNI.new_WireInfo(), true);
  }
}
