/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.apl_cornell.viaduct.libsnarkwrapper;

public class Keypair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Keypair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Keypair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsnarkwrapperJNI.delete_Keypair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProving_key(ByteBuf value) {
    libsnarkwrapperJNI.Keypair_proving_key_set(swigCPtr, this, ByteBuf.getCPtr(value), value);
  }

  public ByteBuf getProving_key() {
    long cPtr = libsnarkwrapperJNI.Keypair_proving_key_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ByteBuf(cPtr, false);
  }

  public void setVerification_key(ByteBuf value) {
    libsnarkwrapperJNI.Keypair_verification_key_set(swigCPtr, this, ByteBuf.getCPtr(value), value);
  }

  public ByteBuf getVerification_key() {
    long cPtr = libsnarkwrapperJNI.Keypair_verification_key_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ByteBuf(cPtr, false);
  }

  public Keypair() {
    this(libsnarkwrapperJNI.new_Keypair(), true);
  }
}
