/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.github.aplcornell.viaduct.libsnarkwrapper;

public class Var {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Var(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Var obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsnarkwrapperJNI.delete_Var(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue(SWIGTYPE_p_libsnark__pb_variableT_field128_t value) {
    libsnarkwrapperJNI.Var_value_set(
        swigCPtr, this, SWIGTYPE_p_libsnark__pb_variableT_field128_t.getCPtr(value));
  }

  public SWIGTYPE_p_libsnark__pb_variableT_field128_t getValue() {
    return new SWIGTYPE_p_libsnark__pb_variableT_field128_t(
        libsnarkwrapperJNI.Var_value_get(swigCPtr, this), true);
  }

  public Var() {
    this(libsnarkwrapperJNI.new_Var(), true);
  }
}
