/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cornell.cs.apl.viaduct.backend.aby;

public final class ABYRole {
  public static final ABYRole ABY_SERVER = new ABYRole("ABY_SERVER");
  public static final ABYRole ABY_CLIENT = new ABYRole("ABY_CLIENT");
  public static final ABYRole ABY_ALL = new ABYRole("ABY_ALL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ABYRole swigToEnum(int swigValue) {
    if (swigValue < swigValues.length
        && swigValue >= 0
        && swigValues[swigValue].swigValue == swigValue) return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue) return swigValues[i];
    throw new IllegalArgumentException("No enum " + ABYRole.class + " with value " + swigValue);
  }

  private ABYRole(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ABYRole(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue + 1;
  }

  private ABYRole(String swigName, ABYRole swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue + 1;
  }

  private static ABYRole[] swigValues = {ABY_SERVER, ABY_CLIENT, ABY_ALL};
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}
