/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cornell.cs.apl.viaduct.backend.aby;

public class AndGate extends BinaryOpGate {
  private transient long swigCPtr;

  protected AndGate(long cPtr, boolean cMemoryOwn) {
    super(ViaductABYJNI.AndGate_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AndGate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ViaductABYJNI.delete_AndGate(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AndGate(CircuitGate lhs, CircuitGate rhs) {
    this(
        ViaductABYJNI.new_AndGate(CircuitGate.getCPtr(lhs), lhs, CircuitGate.getCPtr(rhs), rhs),
        true);
  }
}
