/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cornell.cs.apl.viaduct.backend.aby;

public class CircuitBuilders {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CircuitBuilders(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CircuitBuilders obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ViaductABYJNI.delete_CircuitBuilders(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBitlen(int value) {
    ViaductABYJNI.CircuitBuilders_bitlen_set(swigCPtr, this, value);
  }

  public int getBitlen() {
    return ViaductABYJNI.CircuitBuilders_bitlen_get(swigCPtr, this);
  }

  public void setRole(ABYRole value) {
    ViaductABYJNI.CircuitBuilders_role_set(swigCPtr, this, value.swigValue());
  }

  public ABYRole getRole() {
    return ABYRole.swigToEnum(ViaductABYJNI.CircuitBuilders_role_get(swigCPtr, this));
  }

  public void setArith(SWIGTYPE_p_ArithmeticCircuit value) {
    ViaductABYJNI.CircuitBuilders_arith_set(
        swigCPtr, this, SWIGTYPE_p_ArithmeticCircuit.getCPtr(value));
  }

  public SWIGTYPE_p_ArithmeticCircuit getArith() {
    long cPtr = ViaductABYJNI.CircuitBuilders_arith_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ArithmeticCircuit(cPtr, false);
  }

  public void set_boolean(SWIGTYPE_p_BooleanCircuit value) {
    ViaductABYJNI.CircuitBuilders__boolean_set(
        swigCPtr, this, SWIGTYPE_p_BooleanCircuit.getCPtr(value));
  }

  public SWIGTYPE_p_BooleanCircuit get_boolean() {
    long cPtr = ViaductABYJNI.CircuitBuilders__boolean_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_BooleanCircuit(cPtr, false);
  }

  public void setYao(SWIGTYPE_p_BooleanCircuit value) {
    ViaductABYJNI.CircuitBuilders_yao_set(swigCPtr, this, SWIGTYPE_p_BooleanCircuit.getCPtr(value));
  }

  public SWIGTYPE_p_BooleanCircuit getYao() {
    long cPtr = ViaductABYJNI.CircuitBuilders_yao_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_BooleanCircuit(cPtr, false);
  }

  public CircuitBuilders() {
    this(ViaductABYJNI.new_CircuitBuilders(), true);
  }
}
