/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cornell.cs.apl.viaduct.backend.aby;

public class ViaductABYParty {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ViaductABYParty(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ViaductABYParty obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ViaductABYJNI.delete_ViaductABYParty(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ViaductABYParty(
      ABYRole role, String address, int port, long bitlen, long secparam, long nthreads) {
    this(
        ViaductABYJNI.new_ViaductABYParty__SWIG_0(
            role.swigValue(), address, port, bitlen, secparam, nthreads),
        true);
  }

  public ViaductABYParty(ABYRole role, String address, int port, long bitlen, long secparam) {
    this(
        ViaductABYJNI.new_ViaductABYParty__SWIG_1(
            role.swigValue(), address, port, bitlen, secparam),
        true);
  }

  public ViaductABYParty(ABYRole role, String address, int port, long bitlen) {
    this(ViaductABYJNI.new_ViaductABYParty__SWIG_2(role.swigValue(), address, port, bitlen), true);
  }

  public ViaductABYParty(ABYRole role, String address, int port) {
    this(ViaductABYJNI.new_ViaductABYParty__SWIG_3(role.swigValue(), address, port), true);
  }

  public CircuitGate PutDummyINGate() {
    long cPtr = ViaductABYJNI.ViaductABYParty_PutDummyINGate(swigCPtr, this);
    return (cPtr == 0) ? null : new CircuitGate(cPtr, false);
  }

  public CircuitGate PutINGate(int value) {
    long cPtr = ViaductABYJNI.ViaductABYParty_PutINGate(swigCPtr, this, value);
    return (cPtr == 0) ? null : new CircuitGate(cPtr, false);
  }

  public CircuitGate PutCONSTGate(int value) {
    long cPtr = ViaductABYJNI.ViaductABYParty_PutCONSTGate(swigCPtr, this, value);
    return (cPtr == 0) ? null : new CircuitGate(cPtr, false);
  }

  public CircuitGate PutADDGate(CircuitGate lhs, CircuitGate rhs) {
    long cPtr =
        ViaductABYJNI.ViaductABYParty_PutADDGate(
            swigCPtr, this, CircuitGate.getCPtr(lhs), lhs, CircuitGate.getCPtr(rhs), rhs);
    return (cPtr == 0) ? null : new CircuitGate(cPtr, false);
  }

  public CircuitGate PutSUBGate(CircuitGate lhs, CircuitGate rhs) {
    long cPtr =
        ViaductABYJNI.ViaductABYParty_PutSUBGate(
            swigCPtr, this, CircuitGate.getCPtr(lhs), lhs, CircuitGate.getCPtr(rhs), rhs);
    return (cPtr == 0) ? null : new CircuitGate(cPtr, false);
  }

  public CircuitGate PutMULGate(CircuitGate lhs, CircuitGate rhs) {
    long cPtr =
        ViaductABYJNI.ViaductABYParty_PutMULGate(
            swigCPtr, this, CircuitGate.getCPtr(lhs), lhs, CircuitGate.getCPtr(rhs), rhs);
    return (cPtr == 0) ? null : new CircuitGate(cPtr, false);
  }

  public CircuitGate PutGTGate(CircuitGate lhs, CircuitGate rhs) {
    long cPtr =
        ViaductABYJNI.ViaductABYParty_PutGTGate(
            swigCPtr, this, CircuitGate.getCPtr(lhs), lhs, CircuitGate.getCPtr(rhs), rhs);
    return (cPtr == 0) ? null : new CircuitGate(cPtr, false);
  }

  public CircuitGate PutINVGate(CircuitGate input) {
    long cPtr =
        ViaductABYJNI.ViaductABYParty_PutINVGate(swigCPtr, this, CircuitGate.getCPtr(input), input);
    return (cPtr == 0) ? null : new CircuitGate(cPtr, false);
  }

  public CircuitGate PutANDGate(CircuitGate lhs, CircuitGate rhs) {
    long cPtr =
        ViaductABYJNI.ViaductABYParty_PutANDGate(
            swigCPtr, this, CircuitGate.getCPtr(lhs), lhs, CircuitGate.getCPtr(rhs), rhs);
    return (cPtr == 0) ? null : new CircuitGate(cPtr, false);
  }

  public CircuitGate PutXORGate(CircuitGate lhs, CircuitGate rhs) {
    long cPtr =
        ViaductABYJNI.ViaductABYParty_PutXORGate(
            swigCPtr, this, CircuitGate.getCPtr(lhs), lhs, CircuitGate.getCPtr(rhs), rhs);
    return (cPtr == 0) ? null : new CircuitGate(cPtr, false);
  }

  public CircuitGate PutORGate(CircuitGate lhs, CircuitGate rhs) {
    long cPtr =
        ViaductABYJNI.ViaductABYParty_PutORGate(
            swigCPtr, this, CircuitGate.getCPtr(lhs), lhs, CircuitGate.getCPtr(rhs), rhs);
    return (cPtr == 0) ? null : new CircuitGate(cPtr, false);
  }

  public int ExecCircuit(CircuitGate out, ABYRole out_role) {
    return ViaductABYJNI.ViaductABYParty_ExecCircuit__SWIG_0(
        swigCPtr, this, CircuitGate.getCPtr(out), out, out_role.swigValue());
  }

  public int ExecCircuit(CircuitGate out) {
    return ViaductABYJNI.ViaductABYParty_ExecCircuit__SWIG_1(
        swigCPtr, this, CircuitGate.getCPtr(out), out);
  }

  public void Reset() {
    ViaductABYJNI.ViaductABYParty_Reset(swigCPtr, this);
  }
}
