/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cornell.cs.apl.viaduct.backend.aby;

public class ViaductABYJNI {
  public static final native void CircuitBuilders_bitlen_set(
      long jarg1, CircuitBuilders jarg1_, int jarg2);

  public static final native int CircuitBuilders_bitlen_get(long jarg1, CircuitBuilders jarg1_);

  public static final native void CircuitBuilders_role_set(
      long jarg1, CircuitBuilders jarg1_, int jarg2);

  public static final native int CircuitBuilders_role_get(long jarg1, CircuitBuilders jarg1_);

  public static final native void CircuitBuilders_arith_set(
      long jarg1, CircuitBuilders jarg1_, long jarg2);

  public static final native long CircuitBuilders_arith_get(long jarg1, CircuitBuilders jarg1_);

  public static final native void CircuitBuilders__boolean_set(
      long jarg1, CircuitBuilders jarg1_, long jarg2);

  public static final native long CircuitBuilders__boolean_get(long jarg1, CircuitBuilders jarg1_);

  public static final native void CircuitBuilders_yao_set(
      long jarg1, CircuitBuilders jarg1_, long jarg2);

  public static final native long CircuitBuilders_yao_get(long jarg1, CircuitBuilders jarg1_);

  public static final native long new_CircuitBuilders();

  public static final native void delete_CircuitBuilders(long jarg1);

  public static final native void CircuitGate_AddChildrenToTraversal(
      long jarg1, CircuitGate jarg1_, long jarg2);

  public static final native long CircuitGate_BuildGate(
      long jarg1, CircuitGate jarg1_, long jarg2, long jarg3, CircuitBuilders jarg3_);

  public static final native void delete_CircuitGate(long jarg1);

  public static final native long new_DummyInGate();

  public static final native void DummyInGate_AddChildrenToTraversal(
      long jarg1, DummyInGate jarg1_, long jarg2);

  public static final native long DummyInGate_BuildGate(
      long jarg1, DummyInGate jarg1_, long jarg2, long jarg3, CircuitBuilders jarg3_);

  public static final native void delete_DummyInGate(long jarg1);

  public static final native long new_InGate(long jarg1);

  public static final native void InGate_AddChildrenToTraversal(
      long jarg1, InGate jarg1_, long jarg2);

  public static final native long InGate_BuildGate(
      long jarg1, InGate jarg1_, long jarg2, long jarg3, CircuitBuilders jarg3_);

  public static final native void delete_InGate(long jarg1);

  public static final native long new_InvGate(long jarg1, CircuitGate jarg1_);

  public static final native void InvGate_AddChildrenToTraversal(
      long jarg1, InvGate jarg1_, long jarg2);

  public static final native long InvGate_BuildGate(
      long jarg1, InvGate jarg1_, long jarg2, long jarg3, CircuitBuilders jarg3_);

  public static final native void delete_InvGate(long jarg1);

  public static final native void BinaryOpGate_AddChildrenToTraversal(
      long jarg1, BinaryOpGate jarg1_, long jarg2);

  public static final native long BinaryOpGate_BuildGate(
      long jarg1, BinaryOpGate jarg1_, long jarg2, long jarg3, CircuitBuilders jarg3_);

  public static final native void delete_BinaryOpGate(long jarg1);

  public static final native long new_AddGate(
      long jarg1, CircuitGate jarg1_, long jarg2, CircuitGate jarg2_);

  public static final native void delete_AddGate(long jarg1);

  public static final native long new_SubGate(
      long jarg1, CircuitGate jarg1_, long jarg2, CircuitGate jarg2_);

  public static final native void delete_SubGate(long jarg1);

  public static final native long new_MulGate(
      long jarg1, CircuitGate jarg1_, long jarg2, CircuitGate jarg2_);

  public static final native void delete_MulGate(long jarg1);

  public static final native long new_ConstGate(long jarg1);

  public static final native void ConstGate_AddChildrenToTraversal(
      long jarg1, ConstGate jarg1_, long jarg2);

  public static final native long ConstGate_BuildGate(
      long jarg1, ConstGate jarg1_, long jarg2, long jarg3, CircuitBuilders jarg3_);

  public static final native void delete_ConstGate(long jarg1);

  public static final native long new_GtGate(
      long jarg1, CircuitGate jarg1_, long jarg2, CircuitGate jarg2_);

  public static final native void delete_GtGate(long jarg1);

  public static final native long new_AndGate(
      long jarg1, CircuitGate jarg1_, long jarg2, CircuitGate jarg2_);

  public static final native void delete_AndGate(long jarg1);

  public static final native long new_XorGate(
      long jarg1, CircuitGate jarg1_, long jarg2, CircuitGate jarg2_);

  public static final native void delete_XorGate(long jarg1);

  public static final native long new_OrGate(
      long jarg1, CircuitGate jarg1_, long jarg2, CircuitGate jarg2_);

  public static final native void delete_OrGate(long jarg1);

  public static final native long new_ViaductABYParty__SWIG_0(
      int jarg1, String jarg2, int jarg3, long jarg4, long jarg5, long jarg6);

  public static final native long new_ViaductABYParty__SWIG_1(
      int jarg1, String jarg2, int jarg3, long jarg4, long jarg5);

  public static final native long new_ViaductABYParty__SWIG_2(
      int jarg1, String jarg2, int jarg3, long jarg4);

  public static final native long new_ViaductABYParty__SWIG_3(int jarg1, String jarg2, int jarg3);

  public static final native void delete_ViaductABYParty(long jarg1);

  public static final native long ViaductABYParty_PutDummyINGate(
      long jarg1, ViaductABYParty jarg1_);

  public static final native long ViaductABYParty_PutINGate(
      long jarg1, ViaductABYParty jarg1_, int jarg2);

  public static final native long ViaductABYParty_PutCONSTGate(
      long jarg1, ViaductABYParty jarg1_, int jarg2);

  public static final native long ViaductABYParty_PutADDGate(
      long jarg1,
      ViaductABYParty jarg1_,
      long jarg2,
      CircuitGate jarg2_,
      long jarg3,
      CircuitGate jarg3_);

  public static final native long ViaductABYParty_PutSUBGate(
      long jarg1,
      ViaductABYParty jarg1_,
      long jarg2,
      CircuitGate jarg2_,
      long jarg3,
      CircuitGate jarg3_);

  public static final native long ViaductABYParty_PutMULGate(
      long jarg1,
      ViaductABYParty jarg1_,
      long jarg2,
      CircuitGate jarg2_,
      long jarg3,
      CircuitGate jarg3_);

  public static final native long ViaductABYParty_PutGTGate(
      long jarg1,
      ViaductABYParty jarg1_,
      long jarg2,
      CircuitGate jarg2_,
      long jarg3,
      CircuitGate jarg3_);

  public static final native long ViaductABYParty_PutINVGate(
      long jarg1, ViaductABYParty jarg1_, long jarg2, CircuitGate jarg2_);

  public static final native long ViaductABYParty_PutANDGate(
      long jarg1,
      ViaductABYParty jarg1_,
      long jarg2,
      CircuitGate jarg2_,
      long jarg3,
      CircuitGate jarg3_);

  public static final native long ViaductABYParty_PutXORGate(
      long jarg1,
      ViaductABYParty jarg1_,
      long jarg2,
      CircuitGate jarg2_,
      long jarg3,
      CircuitGate jarg3_);

  public static final native long ViaductABYParty_PutORGate(
      long jarg1,
      ViaductABYParty jarg1_,
      long jarg2,
      CircuitGate jarg2_,
      long jarg3,
      CircuitGate jarg3_);

  public static final native int ViaductABYParty_ExecCircuit__SWIG_0(
      long jarg1, ViaductABYParty jarg1_, long jarg2, CircuitGate jarg2_, int jarg3);

  public static final native int ViaductABYParty_ExecCircuit__SWIG_1(
      long jarg1, ViaductABYParty jarg1_, long jarg2, CircuitGate jarg2_);

  public static final native void ViaductABYParty_Reset(long jarg1, ViaductABYParty jarg1_);

  public static final native long DummyInGate_SWIGUpcast(long jarg1);

  public static final native long InGate_SWIGUpcast(long jarg1);

  public static final native long InvGate_SWIGUpcast(long jarg1);

  public static final native long BinaryOpGate_SWIGUpcast(long jarg1);

  public static final native long AddGate_SWIGUpcast(long jarg1);

  public static final native long SubGate_SWIGUpcast(long jarg1);

  public static final native long MulGate_SWIGUpcast(long jarg1);

  public static final native long ConstGate_SWIGUpcast(long jarg1);

  public static final native long GtGate_SWIGUpcast(long jarg1);

  public static final native long AndGate_SWIGUpcast(long jarg1);

  public static final native long XorGate_SWIGUpcast(long jarg1);

  public static final native long OrGate_SWIGUpcast(long jarg1);
}
