site_name: Viaduct

# Meta tags (placed in header)
site_description: 'Viaduct: an extensible, optimizing compiler for secure distributed programs.'
site_author: Applied Programming Languages Group
site_url: https://viaduct-lang.org

# Repository (adds link to repository on each page)
#repo_name: apl-cornell/viaduct
repo_url: https://github.com/apl-cornell/viaduct
edit_uri: edit/master/docs/src

# Copyright (shown at the footer)
copyright: 'Copyright &copy; 2021 Applied Programming Languages Group'

# Material theme
theme:
  name: material
  features:
    # - navigation.instant # Breaks API reference
    - navigation.tabs
    # - toc.integrate

#  palette:
#    primary: indigo
#    accent: indigo

docs_dir: src

extra:
  version:
    provider: mike
#  social:
#    - type: github
#      link: https://github.com/apl-cornell/viaduct
#    - icon: fontawesome/brands/docker
#      link: https://hub.docker.com/repository/docker/cacay/viaduct

extra_css:
  - assets/stylesheets/extra.css

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde

nav:
  - Home:
      - index.md
      - user-guide/getting-started.md
      - user-guide/compiling-and-running.md
  - Developer's Guide:
      - developer-guide/building.md
      - developer-guide/logging.md
      - developer-guide/dependencies.md
      - developer-guide/documentation.md
  - API Reference:
      - api/index.html
