name: CI

on: [ push, pull_request ]

env:
  JDK_DISTRIBUTION: zulu

jobs:
  build:
    name: build (${{ matrix.os }}, JDK ${{ matrix.java }})

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        java: [ 11 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ matrix.java }}
      - name: Build and test the compiler
        uses: gradle/gradle-build-action@v2
        with:
          arguments: printVersion build jacocoTestReport
      - name: Build example programs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -p examples build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
