name: CI

on: [ push, pull_request ]

env:
  JDK_DISTRIBUTION: zulu

jobs:
  build:
    name: build (${{ matrix.os }}, JDK ${{ matrix.java }})

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        java: [ 17 ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build and test the compiler
        run: ./gradlew printVersion build jacocoTestReport
      - name: Build example programs
        run: ./gradlew -p examples build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
