name: Documentation

on:
  push:
  pull_request:
  release:
    types: [ published ]

env:
  JDK_DISTRIBUTION: zulu
  JDK_VERSION: 11

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v2
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ env.JDK_VERSION }}
      - name: Install pipenv
        run: pipx install pipenv
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - name: Generate documentation with MkDocs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: printVersion :docs:mkdocsBuild
      - name: Publish documentation to GitHub Pages
        if: github.event_name == 'release'
        uses: gradle/gradle-build-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          arguments: :docs:mkdocsPublish
