name: Documentation

on:
  push:
  pull_request:
  release:
    types: [ published ]

env:
  JDK_DISTRIBUTION: zulu
  JDK_VERSION: 11

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v2
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ env.JDK_VERSION }}
      - name: Generate documentation with MkDocs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: mkdocsBuild
      - name: Publish documentation to GitHub Pages
        if: github.event_name == 'release'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/mkdocs
          keep_files: true
