name: Documentation

on: [ push, pull_request ]

jobs:
  documentation:
    runs-on: ubuntu-latest

    env:
      java: 11

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ env.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java }}
      - name: Generate documentation with MkDocs
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: mkdocsBuild
      - name: Upload to GitHub Pages
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: mkdocsPublish
        env:
          GRGIT_USER: ${{ secrets.GITHUB_TOKEN }}
