name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * *"

env:
  JDK_DISTRIBUTION: zulu
  JDK_VERSION: 17

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ env.JDK_VERSION }}

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
